name: Build and push

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and push image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker build -t ringfungi/platform-engineer:latest .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push ringfungi/platform-engineer:latest
