name: Build and push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push multi-arch images
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_NAME: "ringfungi/platform-engineer"
        run: |
          docker buildx create --use
          docker buildx inspect --bootstrap
          
          # Build and tag for x86_64
          docker buildx build --platform linux/amd64 -t $IMAGE_NAME:latest .
          
          # Build and tag for ARM
          docker buildx build --platform linux/arm/v7 -t $IMAGE_NAME:latest-arm .
          
          # Login to Docker Hub
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          
          # Push both images
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:latest-arm
